### ISSUE TITLE
Readme has incorrect link to example.json for GMCQ

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-graphic#46]
Ln 31 of readme has [example.json](https://github.com/adaptlearning/adapt-contrib-gmcq/blob/master/example.json). Should be [example.json](https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/example.json).

**Comment by dancgray** [comment]
Needs applying to master as well

**Comment by zenduo** [comment]
Hey Dan, have these been submitted for PR?

**Comment by dancgray** [comment]
Hi @zenduo, new PR for example change in master: https://github.com/adaptlearning/adapt-contrib-graphic/pull/48

Develop branch has already been merged (https://github.com/adaptlearning/adapt-contrib-graphic/pull/47)

**Comment by zenduo** [comment]
Perfect, i'll get the master pushed through then we can close this issue off.
