### ISSUE TITLE
Transform

### ISSUE THREAD

**Issue by oghmios** [adaptlearning/adapt-contrib-graphic#58]
Where it does _graphic.large=_graphic.src?

**Comment by moloko** [comment]
https://github.com/adaptlearning/adapt-contrib-graphic/blob/master/js/adapt-contrib-graphic.js#L51

**Comment by oghmios** [comment]
But that function receives a "width" parameter to work."How I can send more parameters?

**Comment by oliverfoster** [comment]
You'll need to describe what you want to do to the graphic. It's difficult to help with what you've written so far.

**Comment by oghmios** [comment]
yes, i'm sorry. I want to put two images instead one, and I put in .hbs the new variables to recognise the div and the rest of the arguments, but when I build the framework, it put the first image in two divs. If you see the information, data_large= correct url, but src= is different

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#847
