### ISSUE TITLE
Accessibility enhancement? Long description toggle

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt-contrib-graphic#82]
Wondering if there would be any appetite to include an additional long description text field to allow adding a "long description" of infographic type graphics.

See this URL for an nice simple implementation. It means the pages are not initially overly long and the additional information is available to all users.

https://psu.instructure.com/courses/2004931/pages/long-description-examples-charts?module_item_id=30603503

**Comment by oliverfoster** [comment]
Yes please. What were you thinking, graphic only?

**Comment by paul-mediakitchen** [comment]
I am thinking that would be the most likely place you would add an info graphic though I am sure there could be use cases in other components that include graphic elements but want to keep this manageable.
